[package]
name = "rlunar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
chrono = "0.4"
anyhow = "1.0"

[dev-dependencies]
rstest = "0.18.2"
#chrono-tz = "0.8"
